version: '3.8'

services:

  app:
    build: .
    command: npm run dev
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mediq-network
    restart: unless-stopped

volumes:
  ollama_data:

networks:
  mediq-network:
    driver: bridge